### ISSUE TITLE
Consider adding URL whitelist mechanism to agent(考虑对agent加入url白名单机制)

### ISSUE THREAD

**Issue by langligelang** [HXSecurity/DongTai-agent-java#133]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Because a large number of heartbeat packets need to be sent, and for these heartbeat packets, the agent will send a request to the server every time, which will consume more time. Performance degradation. Want to join the URL whitelist mechanism. Some URLs are not detected by default.
因为有大量的心跳包需要发送，而对于这些心跳包，每发送一次agent就会发送一个请求到server，这样会消耗比较多的时间。使得性能下降。想要加入url白名单机制。默认不检测某些url。

### Proposed Solution

Faster(更快)

**Comment by zzzskd** [comment]
@exexute Hello master, how to use this feature, is there any documentation to refer to?
