### ISSUE TITLE
Add configurable proxy IP and port to realize the linkage between IAST and DAST

### ISSUE THREAD

**Issue by langligelang** [HXSecurity/DongTai-agent-java#214]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Add configurable proxy IP and port to realize the linkage between IAST and DAST
新增对agent可配置的代理ip和端口，实现IAST 和DAST的联动。

### Proposed Solution

Realize the outgoing traffic and hit the self-realized DAST within the enterprise
实现流量的外发，打到企业内部自实现的DAST

**Comment by lostsnow** [comment]
We have successfully integrated DongTai IAST and X-Ray, for further information please refer to the following two articles:

* https://i0x0fy4ibf.feishu.cn/docx/X51kdnWmRoVbu8xPNtWcsNAynTg
* https://i0x0fy4ibf.feishu.cn/wiki/wikcn9hKakyNnTOaul4E89vMblh

As for other DAST tools, they can be adapted by referencing the project https://github.com/HXSecurity/Dongtai_USB.
