### ISSUE TITLE
[Feature] Add attach parameter

### ISSUE THREAD

**Issue by Nizernizer** [HXSecurity/DongTai-agent-java#255]
Add two parameter:
```
dongtai_server
dongtai_token
```

**Comment by exexute** [comment]
Version: 1.3.1 
Doc: https://doc.dongtai.io/docs/getting-started/agent/parameter/config-java-agent

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/16431735/156998583-f41da91b-0183-4a78-b0b0-07bfaa1266c1.png">
