### ISSUE TITLE
SCAScanner.java命名不规范导致maven编译失败

### ISSUE THREAD

**Issue by tcsecchen** [HXSecurity/DongTai-agent-java#3]
iast-core/src/main/java/com/secnium/iast/core/enhance/sca/SCAScanner.java
应该为ScaScanner

![图片](https://user-images.githubusercontent.com/25191604/114156913-a5ed6300-9955-11eb-9129-d419235dd7c8.png)

**Comment by BiteFoo** [comment]
我也提提了这个问题，大E了

**Comment by exexute** [comment]
已解决
