### ISSUE TITLE
[Bug]: 洞态无法加载agent

### ISSUE THREAD

**Issue by G0mini** [HXSecurity/DongTai-agent-java#369]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

最新版本

### Installation Type

Official Docker Compose

### Service Name

DongTai-agent-java

### Describe the details of the bug and the steps to reproduce it

server使用centos7.9-docker部署。拉取最新版本。
部署参考：
https://zone.huoxian.cn/d/2552-iastsqlbypasscve
![3972a48c922118604f667e479c35b5b](https://user-images.githubusercontent.com/31945727/190595443-16af98cd-a476-463c-891d-724ffc557722.jpg)

客户端用windows部署。
tomcat版本:apache-tomcat-9.0.56
cms使用jspxcms测试。

无法加载agent。一直错误
![image](https://user-images.githubusercontent.com/31945727/190595345-08d75362-4cf5-4526-bbdf-194ad7591da7.png)

**Comment by lostsnow** [comment]
Are you running the process with Adminstrator? If so it could be this problem: https://github.com/apangin/jattach/issues/23, and we need to upgrade jattach for agent

**Comment by lostsnow** [comment]
This issue has been resolved in v1.10.0 of the agent.
