### ISSUE TITLE
[Feature]: Java Agent是否可以增加Tomcat7的兼容

### ISSUE THREAD

**Issue by KKhit** [HXSecurity/DongTai-agent-java#375]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.

### Problem Description

目前Java Agent支持的tomcat中间件只有8，9版本，但是我们使用的tomcat7占比更多，目前无法支持tomcat7大批量升级，所以是否可以进行Tomcat7的兼容

### Proposed Solution

Java Agent可以增加Tomcat7的兼容

**Comment by lostsnow** [comment]
At the moment, there is no such plan in place.
