### ISSUE TITLE
[Bug]: 触发性能阈值后卸载不彻底，导致大量报错

### ISSUE THREAD

**Issue by fengzhouc** [HXSecurity/DongTai-agent-java#399]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.7.7

### Installation Type

Official Kubernetes

### Service Name

DongTai-Core, DongTai-agent-java

### Describe the details of the bug and the steps to reproduce it

pod在启动的时候出现了性能压力，所以dongtai 的agent自动卸载了
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/22309037/196578122-b4a5fb30-a3ff-4294-a06b-bfe7e9e0981f.png">
但是这个卸载可能存在bug，因为agent还是注入了dubbo的入口。
<img width="721" alt="image" src="https://user-images.githubusercontent.com/22309037/196578167-d801c262-4e09-4f7d-af1a-ba6756352db8.png">

**Comment by lostsnow** [comment]
try upgrade agent to 1.7.8
