### ISSUE TITLE
Agent ips are not displayed accurately on the server side

### ISSUE THREAD

**Issue by Windy-Yang** [HXSecurity/DongTai-agent-java#421]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.9.0

### Installation Type

Official Docker Compose

### Describe the details of the bug and the steps to reproduce it

agent在web端展示的ip与本机IP不一致，并不是获取的本机的ip，而是一张虚拟网卡的ip

**Comment by lostsnow** [comment]
upgrade the dongtai server to 1.9.2 will fix this problem
