### ISSUE TITLE
java agent自动部署时没有应用漏洞 agent安装时只存在一个硬编码漏洞

### ISSUE THREAD

**Issue by bbg8cody** [HXSecurity/DongTai-agent-java#438]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai-agent-java/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai-agent-java/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai-agent-java/issues/new/choose) without success.

### Version

1.9.1

### Installation Type

Official Kubernetes

### Describe the details of the bug and the steps to reproduce it

用k8s部署时在线拉的洞态不是离线下载的，
现在的情况是用自动部署的命令安装时，应用漏洞是空的，用java agent命令安装时只存在一个硬编码漏洞
![image](https://user-images.githubusercontent.com/45092826/208071164-6c66405c-93ee-467b-95b4-5cc27ca6b283.png)

问微信群说是要看debug日志，报错的只有这段
![image](https://user-images.githubusercontent.com/45092826/208071246-484a6d57-6465-4752-8941-5b2b65241d39.png)

还想问下就是docker类型的java业务该怎么部署，用自动命令安装会失败

**Comment by lostsnow** [comment]
upgrade the agent version to 1.8.1 will fix this problem
