### ISSUE TITLE
[Bug]: 装完javaagent之后cpu飙到400%

### ISSUE THREAD

**Issue by PhuketIsland** [HXSecurity/DongTai-agent-java#512]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.9.3

### Installation Type

Official Kubernetes

### Service Name

DongTai-agent-java

### Describe the details of the bug and the steps to reproduce it

1.java环境，使用java -jar dongtai-agent.jar -m install -p 1  添加java agent并成功上线
![image](https://user-images.githubusercontent.com/28825226/233889944-73322320-3847-4a17-8157-7308eef02479.png)
然后cpu就开始持续上升，知道百分之400多
<img width="944" alt="企业微信截图_84c852a2-5ee8-4127-b1e5-3ba64ec088e1" src="https://user-images.githubusercontent.com/28825226/233890055-482dd2dc-8afa-4ec4-9c0c-43761c0735d2.png">

### Logs

```shell
日志没有了
```

**Comment by PhuketIsland** [comment]
![image](https://user-images.githubusercontent.com/28825226/233910991-ebb1f6d4-e65c-4d75-98b2-4293f08575d0.png)

**Comment by Nizernizer** [comment]
可以使用arthas或Jprofile等工具导出cpu热点图，便于开发者排查。
