### ISSUE TITLE
[Bug]: fastjson已经是1.2.83版本了，洞态显示请求头有反序列化漏洞

### ISSUE THREAD

**Issue by PhuketIsland** [HXSecurity/DongTai-agent-java#533]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.11.0

### Installation Type

Official SaaS Service

### Service Name

DongTai-agent-java

### Describe the details of the bug and the steps to reproduce it

![image](https://github.com/HXSecurity/DongTai/assets/28825226/0184d78d-e070-4be4-b069-aaf2065c9d3a)
污点流程图
![image](https://github.com/HXSecurity/DongTai/assets/28825226/d8638f70-9be5-43d2-9c37-f85caf9e9603)
危险方法显示是fastjson
![image](https://github.com/HXSecurity/DongTai/assets/28825226/79cf4cfb-3544-4352-97c9-84ed54554b28)
但是fastjson目前已经是最新版本 1.2.83 ,这是否是误报？不是误报的话又该怎么验证

**Comment by lostsnow** [comment]
Could you provide the pom.xml file of the project?

**Comment by lostsnow** [comment]
Additionally, could you decompile the project's jar file and check the value of the VERSION field in the `com.alibaba.fastjson.JSON` class?

**Comment by PhuketIsland** [comment]
@lostsnow 你好    抱歉pom.xml和字段值目前都提供不了，但是验证失败跟这个漏洞是否存在有没有必然联系呢？

**Comment by lostsnow** [comment]
The verification results are irrelevant. This vulnerability is mainly related to the version number of Fastjson and whether safemode is enabled (for older versions of Fastjson).

**Comment by lostsnow** [comment]
The issue has been identified. A bug caused the fastjson class to not match, leading to false positives. This bug will be rectified in v1.12.0

**Comment by PhuketIsland** [comment]
@lostsnow 收到 感谢
