### ISSUE TITLE
[Bug]: POST出现服务器端请求伪造漏洞,位置:HEADER

### ISSUE THREAD

**Issue by PhuketIsland** [HXSecurity/DongTai-agent-java#538]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.12.0

### Installation Type

Official Kubernetes

### Service Name

DongTai-Web

### Describe the details of the bug and the steps to reproduce it

![image](https://github.com/HXSecurity/DongTai/assets/28825226/b9918e2a-0816-4b39-9b9b-452509b8c1c4)
根据调用链显示x-forwarded-for参数存在ssrf的注入点，我将洞态上的请求复制到burp上重新发从，发现将x-forwarded-for这个参数删除之后仍然可以得到响应结果，这个是不是误报？
![image](https://github.com/HXSecurity/DongTai/assets/28825226/3d4e2780-8d32-417b-b7d4-7c72681e94d8)
![image](https://github.com/HXSecurity/DongTai/assets/28825226/f53fe931-acb6-48b2-84f2-38a075361fd6)

**Comment by lostsnow** [comment]
Could youprovide the complete method pool information? It can be found from the field "method_pool" in the table "iast_agent_method_pool" of the database. Please remember to obfuscate any sensitive information.

**Comment by PhuketIsland** [comment]
[iast_agent_method_pool.txt](https://github.com/HXSecurity/DongTai-agent-java/files/11890575/iast_agent_method_pool.txt)
@lostsnow 这些是我查出来的相关数据

**Comment by lostsnow** [comment]
What is the JDK version for this project? method `StringConcatHelper.prepend(int,byte[],byte,java.lang.String)` causes a widening of the taint propagation process, here we need to investigate whether we can accurately calculate the actual position of the taint in the return value of the method , if it is possible to do so, we can prevent false positives

**Comment by PhuketIsland** [comment]
已经确定了是误报吗？
@lostsnow   这是JDK版本
![image](https://github.com/HXSecurity/DongTai-agent-java/assets/28825226/296fcb7e-5f19-46f4-ba5a-a7dc839eac8e)
![image](https://github.com/HXSecurity/DongTai-agent-java/assets/28825226/b784ed4e-33dd-4cf5-9fe3-c7cf21fc5d34)
